import React, { useCallback, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useFocusEffect } from '@react-navigation/native';
import { authService, localDataService } from '../../services/api';
import { SPACING, TYPOGRAPHY } from '../../styles/theme';

const BRAND = { bg:'#F6F8FC', panel:'#FFF', text:'#0A1A33', secondary:'#5C6B89', accent:'#2F5FD8', line:'rgba(10,26,51,.12)' };
export default function SavedScreen({ navigation }) {
  const [items, setItems] = useState([]); const [user, setUser] = useState(null); const [query, setQuery] = useState('');
  const load = useCallback(async () => { const current = await authService.getCurrentUser(); setUser(current); if (current) setItems(await localDataService.get(localDataService.keyForUser('saved', current.id))); }, []);
  useFocusEffect(useCallback(() => { load(); }, [load]));
  const remove = (item) => Alert.alert('Remover de Salvos', 'O conteúdo original não será excluído.', [{text:'Cancelar',style:'cancel'}, {text:'Remover',style:'destructive',onPress:async()=>{const next=items.filter((entry)=>entry.id!==item.id);setItems(next);await localDataService.set(localDataService.keyForUser('saved',user?.id),next);}}]);
  const visible = items.filter((item) => `${item.title} ${item.content || ''}`.toLowerCase().includes(query.toLowerCase()));
  return <View style={styles.container}><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}><View style={styles.hero}><TouchableOpacity onPress={() => navigation.goBack()} style={styles.back}><Feather name="arrow-left" size={19} color={BRAND.text}/></TouchableOpacity><Text style={styles.title}>Salvos</Text><Text style={styles.copy}>Conteúdos que você decidiu guardar.</Text></View><View style={styles.content}><View style={styles.search}><Feather name="search" size={18} color={BRAND.secondary}/><TextInput value={query} onChangeText={setQuery} placeholder="Pesquisar em Salvos" placeholderTextColor={BRAND.secondary} style={styles.searchInput}/></View><Text style={styles.category}>Todos · Notas</Text>{visible.length===0?<View style={styles.empty}><Feather name="bookmark" size={25} color={BRAND.accent}/><Text style={styles.emptyText}>{items.length ? 'Nenhum item encontrado.' : 'Nenhum conteúdo salvo.'}</Text></View>:visible.map((item)=><TouchableOpacity key={item.id} onPress={() => navigation.navigate('App',{screen:'MainTabs',params:{screen:'Notes'}})} style={styles.item}><View style={styles.icon}><Feather name="file-text" size={18} color={BRAND.accent}/></View><View style={styles.itemBody}><Text style={styles.itemTitle} numberOfLines={1}>{item.title}</Text><Text style={styles.itemContent} numberOfLines={2}>{item.content || 'Nota salva'}</Text></View><TouchableOpacity hitSlop={10} onPress={() => remove(item)}><Feather name="x" size={20} color={BRAND.secondary}/></TouchableOpacity></TouchableOpacity>)}</View></ScrollView></View>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:BRAND.bg},scroll:{paddingBottom:32},hero:{backgroundColor:BRAND.panel,paddingTop:52,paddingHorizontal:SPACING.lg,paddingBottom:22,borderBottomWidth:1,borderColor:BRAND.line},back:{width:40,height:40,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:BRAND.line,borderRadius:9,marginBottom:14},title:{fontSize:28,fontWeight:'600',color:BRAND.text},copy:{fontSize:TYPOGRAPHY.small,color:BRAND.secondary,marginTop:7},content:{padding:SPACING.lg},search:{height:46,borderWidth:1,borderColor:BRAND.line,borderRadius:10,backgroundColor:BRAND.panel,flexDirection:'row',alignItems:'center',paddingHorizontal:12,gap:8},searchInput:{flex:1,color:BRAND.text,fontSize:14},category:{fontSize:12,color:BRAND.accent,fontWeight:'700',marginVertical:18},empty:{backgroundColor:BRAND.panel,borderRadius:14,borderWidth:1,borderColor:BRAND.line,alignItems:'center',gap:9,paddingVertical:34},emptyText:{color:BRAND.secondary,fontWeight:'600'},item:{backgroundColor:BRAND.panel,borderRadius:13,borderWidth:1,borderColor:BRAND.line,padding:13,flexDirection:'row',alignItems:'center',gap:12,marginBottom:10},icon:{width:38,height:38,borderRadius:9,backgroundColor:'#E8EFFD',alignItems:'center',justifyContent:'center'},itemBody:{flex:1},itemTitle:{fontSize:15,fontWeight:'700',color:BRAND.text},itemContent:{fontSize:12,lineHeight:17,color:BRAND.secondary,marginTop:3}});
